site_name: cubao-python
site_url: https://cubao-python.readthedocs.io
site_description: misc python scripts of cubao
site_author: district10

repo_url: https://github.com/cubao/cubao-python
edit_uri: blob/main/docs/

theme: readthedocs
nav:
    - Home: index.md
    - Usage: usage.md
    - About:
        - Release Notes: about/release-notes.md
        - License: about/license.md
plugins:
  - include-markdown
copyright: Copyright &copy; 2023 <a href="https://github.com/cubao">cubao team</a>.
